config/routes.rb
Rails.application.routes.draw do
  resources :calc_grads
  resources :multipliers
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calc_grad.rb
class CalcGrad < ApplicationRecord
end

app/models/multiplier.rb
class Multiplier < ApplicationRecord
  validates :multiplier_name, presence: true

  def retrieve(major)
    if major == "Computer Science"
      self.multiplier_name = "Games Released on Steam"
      self.multiplier_value = 21
    end
  end
  
end

app/models/student.rb
class Student < ApplicationRecord

  
  def class_standing
    if(credits < 50)
      "Freshman"
    elsif (credits < 90)
      "Sophomore"
    elsif (credits < 135)
      "Junior"
    else
      "Senior"
    end
  end

  def caluclate_time_until_graduation
    if (self.class_standing == "Freshman")
      self.days_until_graduation = 1460
    elsif (self.class_standing == "Sophomore")
      self.days_until_graduation = 1095
    elsif (self.class_standing == "Junior")
      self.days_until_graduation = 730
    else
      self.days_until_graduation = 365
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calc_grad_controller.rb
class CalcGradController < ApplicationController
  def index
    @multipliers = Multiplier.all
    @students = Student.all
  end
end

app/controllers/calc_grads_controller.rb
class CalcGradsController < ApplicationController
  def index
    @multipliers = Multiplier.all
    @students = Student.all
    @student_options = Student.all.map { |student| student.student_name}
  end
end

app/controllers/multipliers_controller.rb
class MultipliersController < ApplicationController
  def new
    @multiplier = Multiplier.new
  end
  
  def index
    @multiplier = Multiplier.all
  end
  
  def create
    @workflow = CreatesMultiplier.new(
    multiplier_name: params[:multiplier][:multiplier_name],
    multiplier_value: params[:multiplier][:multiplier_value])
    @workflow.create
    redirect_to multipliers_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end
  
  def index
    @student = Student.all
  end
  
  def create
    @workflow = CreatesStudent.new(
    student_name: params[:student][:student_name],
    days_until_graduation: params[:student][:days_until_graduation],
    credits: params[:student][:credits],
    declared_major: params[:student][:declared_major])
    @workflow.create
    redirect_to students_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calc_grads_helper.rb
module CalcGradsHelper
end

app/helpers/multipliers_helper.rb
module MultipliersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/calc_grad/index.html.erb
<h1> Calculating Graduation Times </h1>
<table>
  <thead>
    <tr>
      <td>Student</td>
      <td>Credits</td>
      <td>Major</td>
      
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.credits %></td>
      <td><%= student.declared_major %></td>
      <!-- <td><%= student.days_until_graduation %></td> -->
    </tr>
    <% end %>
  </tbody>
</table>

</br>
</br>

<table>
  <thead>
    <tr>
      <td>Multiplier</td>
      <td>Mult Value</td>     
    </tr>
  </thead>
    <tbody>
    <% @multipliers.each do |multiplier| %>
    <tr>
      <td><%= multiplier.name %></td>
      <td><%= multiplier.multiplier_value %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</br>
</br>

<div>
   <td>Days until graduation</td>
</div>

app/views/calc_grads/index.html.erb
<h1> Calculating Graduation Times </h1>

<%= link_to 'Manage Students', students_path %>
<table>
  <thead>
    <tr>
      <td>Student</td>
      <td>Credits</td>
      <td>Major</td>
      
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.student_name %></td>
      <td><%= student.credits %></td>
      <td><%= student.declared_major %></td>
      <!-- <td><%= student.days_until_graduation %></td> -->
    </tr>
    <% end %>
  </tbody>
</table>

</br>
</br>

<%= link_to 'Manage Multipliers', multipliers_path %>
<table>
  <thead>
    <tr>
      <td>Multiplier</td>
      <td>Mult Value</td>     
    </tr>
  </thead>
    <tbody>
    <% @multipliers.each do |multiplier| %>
    <tr>
      <td><%= multiplier.multiplier_name %></td>
      <td><%= multiplier.multiplier_value %></td>
    </tr>
    <% end %>
  </tbody>
</table>

</br>
</br>

<div>
   <td>Days until graduation</td>
   <div id="calc_grad_form">
     <%= select_tag 'student_name', 
      options_from_collection_for_select(@students, "student_name", "student_name"), include_blank: "Select Student Name" %>
     <%= select_tag 'multiplier', options_for_select(@multipliers.collect { |multiplier| multiplier.multiplier_value }), include_blank: "Select Multiplier" %>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraduationCountdown</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/multipliers/index.html.erb
<h1>All Multipliers</h1>
<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Value</td>
    </tr>
  </thead>
  <tbody>
    <% @multiplier.each do |multiplier| %>
      <tr class="multiplier-row" id="<%= dom_id(multiplier) %>">
        <td class="multiplier_name"><%= multiplier.multiplier_name %></td>
        <td class = "multiplier_value"><%= multiplier.multiplier_value %></td>
      </tr>
    <% end %>
  </tbody>
  <%= link_to 'New', new_multiplier_path %>
</table>

app/views/multipliers/new.html.erb
<h1>New Multiplier</h1>

<%= form_for(@multiplier) do |f| %>
   <%= f.label :multiplier_name %>
   <%= f.text_field :multiplier_name %>
   <br />
   <%= f.label :multiplier_value %>
   <%= f.text_field :multiplier_value %>
   <br />
   <%= f.submit "Create Multiplier"%>
<% end %>

app/views/students/index.html.erb
<h1> All Students </h1>
<table>
	<thead>
		<tr>
			<td><pre>Student Name</pre></td>
			<td><pre>Credits </pre></td>
			<td><pre>Declared Major </pre></td>
			<td><pre>Days until graduation </pre></td>
		</tr>
	</thead>
	<tbody>
		<% @student.each do |students| %>
		<tr>
			<td><%= students.student_name %></td>
			<td><%= students.credits %></td>
			<td><%= students.declared_major %></td>
			<td><%= students.caluclate_time_until_graduation %></td>
		</tr>
		<% end %>
	</tbody>

	<%= link_to 'New', new_student_path %>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>
<%= form_for(@student) do |f| %> 
  <%= f.label :student_name %> 
  <%= f.text_field :student_name %>
  <br/>
	<%= f.label :declared_major %> 
	<%= f.text_field :declared_major %>
	<br/>
	<%= f.label :credits %>
	<%= f.text_field :credits %>
	<br/>
	<%= f.submit "Create Student" %> 
<% end %> 